process DIAUMPIRE {
    tag "${meta.id}"
    label 'process_high'

    container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
        'docker://fcyucn/fragpipe:24.0' :
        'docker.io/fcyucn/fragpipe:24.0' }"

    input:
    // DIA-Umpire generates pseudo-spectra from DIA data
    // dia_file: DIA mass spec file (mzML, mzXML, or raw)
    // config_file: DIA-Umpire params file (coupled with sample inputs)
    tuple val(meta), path(dia_file), path(config_file)

    output:
    tuple val(meta), path("${prefix}")                          , emit: results_dir
    tuple val(meta), path("${prefix}/*_Q1.mzML")                , emit: q1_spectra, optional: true
    tuple val(meta), path("${prefix}/*_Q2.mzML")                , emit: q2_spectra, optional: true
    tuple val(meta), path("${prefix}/*_Q3.mzML")                , emit: q3_spectra, optional: true
    tuple val(meta), path("${prefix}/*_Q*.mgf")                 , emit: mgf_spectra, optional: true
    tuple val("${task.process}"), val('diaumpire'), eval("cat .diaumpire_version"), emit: versions_diaumpire, topic: versions
    tuple val("${task.process}"), val('fragpipe'), eval("cat .fragpipe_version"), emit: versions_fragpipe, topic: versions

    when:
    task.ext.when == null || task.ext.when

    script:
    def args = task.ext.args ?: ''
    prefix = task.ext.prefix ?: "${meta.id}"
    def ram = task.memory ? Math.max(1, task.memory.toGiga() - 2) : 30
    def tools_dir = task.ext.fragpipe_tools_dir ?: '/fragpipe_bin/fragpipe-24.0/fragpipe-24.0/tools'

    """
    
    export HOME=\$(pwd)
    mkdir -p ${prefix}

    TOOLS_DIR="${tools_dir}"

    DIAUMPIRE_JAR=\$(find "\$TOOLS_DIR" -name 'DIA_Umpire*.jar' -type f 2>/dev/null | head -1 || true)
    BATMASS_JAR=\$(find "\$TOOLS_DIR" -name 'batmass-io*.jar' -type f 2>/dev/null | head -1 || true)
    THERMO_DIR="${tools_dir}/../ext/thermo"
    _ver=\$(java -jar "\$DIAUMPIRE_JAR" 2>&1 | grep -oP 'version: v\\K[\\d.]+' | head -1 || true)

    echo "\$_ver" > .diaumpire_version
    _fp_ver=\$(echo "\$TOOLS_DIR" | grep -oP 'fragpipe-\\K[0-9]+\\.[0-9]+[0-9.]*' | head -1 || true)

    echo "\$_fp_ver" > .fragpipe_version
    NATIVE_FLAGS=""
    [ -d "\$THERMO_DIR" ] && NATIVE_FLAGS="-Dlibs.thermo.dir=\$THERMO_DIR"

    # DIA-Umpire SE (Signal Extraction) - generates pseudo-spectra from DIA data
    # Output: *_Q1.mzML, *_Q2.mzML, *_Q3.mzML (quality tiers)
    if [ -s "${config_file}" ]; then
        PARAMS_FILE="${config_file}"
    else
        # No config provided — create minimal params file with DIA-Umpire defaults
        PARAMS_FILE="diaumpire_defaults.params"
        cat > "\$PARAMS_FILE" <<PARAMS
# DIA-Umpire SE default parameters (generated by module)
SE.MS1PPM = 10
SE.MS2PPM = 20
SE.NoMissedScan = 1
SE.EstimateBG = true
SE.IsosN = 2
SE.MassDefectFilter = true
SE.MassDefectOffset = 0.1
PARAMS
    fi

    export JAVA_OPTS="-Xmx${ram}G"
    CMD="java \$JAVA_OPTS \$NATIVE_FLAGS -cp \\"\$DIAUMPIRE_JAR:\$BATMASS_JAR\\" dia_umpire_se.DIA_Umpire_SE ${dia_file} \$PARAMS_FILE ${args}"
    printf '%s\\n' "\$CMD" > ${prefix}/diaumpire.log
    eval "\$CMD" 2>&1 | tee -a ${prefix}/diaumpire.log

    # Move output files to prefix directory
    shopt -s nullglob
    for f in *_Q1.mzML *_Q2.mzML *_Q3.mzML *_Q1.mgf *_Q2.mgf *_Q3.mgf; do cp -L "\$f" ${prefix}/; done
    shopt -u nullglob

    """

    stub:
    prefix = task.ext.prefix ?: "${meta.id}"
    def basename = dia_file.baseName
    """
    mkdir -p ${prefix}
    touch ${prefix}/${basename}_Q1.mzML
    touch ${prefix}/${basename}_Q2.mzML
    touch ${prefix}/${basename}_Q3.mzML
    touch ${prefix}/diaumpire.log
    TOOLS_DIR="${task.ext.fragpipe_tools_dir ?: '/fragpipe_bin/fragpipe-24.0/fragpipe-24.0/tools'}"
    _fp_ver=\$(echo "\$TOOLS_DIR" | grep -oP 'fragpipe-\\K[0-9]+\\.[0-9]+[0-9.]*' | head -1 || true)
    echo "\$_fp_ver" > .diaumpire_version
    echo "\$_fp_ver" > .fragpipe_version

    """
}
