name: diannr
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base=4.4.1
  - conda-forge::r-essentials
  - conda-forge::r-devtools
  # NOTE: diann-rpackage is not available on conda; installed from GitHub in Docker image
